# Generated by Django 6.0.4 on 2026-05-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='Moscow', max_length=50, verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
